// Generated by CoffeeScript 1.12.6
var $, ipcRenderer;

ipcRenderer = require('electron').ipcRenderer;

$ = require('jquery');

ipcRenderer.on('scmex', function(arg) {
  var div;
  div = (function() {
    switch (arg) {
      case 'pressed-1':
        return $('#n1');
      case 'pressed-2':
        return $('#n2');
      default:
        return null;
    }
  })();
  return div != null ? div.click() : void 0;
});
